
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS EXIT HELP NAME createScale playScale\n    assign : func\n          | NAME EQUALS assign_createScale\n    \n    assign_createScale : createScale NAME NAME\n    \n    assign_playScale : playScale assign_createScale\n                    | playScale\n                    | playScale NAME\n    \n    func : assign_createScale\n        | assign_playScale\n        | HELP\n        | EXIT\n    '
    
_lr_action_items = {'NAME':([0,8,9,11,],[3,11,13,15,]),'HELP':([0,],[6,]),'EXIT':([0,],[7,]),'createScale':([0,9,10,],[8,8,8,]),'playScale':([0,],[9,]),'$end':([1,2,4,5,6,7,9,12,13,14,15,],[0,-1,-7,-8,-9,-10,-5,-4,-6,-2,-3,]),'EQUALS':([3,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assign':([0,],[1,]),'func':([0,],[2,]),'assign_createScale':([0,9,10,],[4,12,14,]),'assign_playScale':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign","S'",1,None,None,None),
  ('assign -> func','assign',1,'p_assign','PySharp_Parse.py',11),
  ('assign -> NAME EQUALS assign_createScale','assign',3,'p_assign','PySharp_Parse.py',12),
  ('assign_createScale -> createScale NAME NAME','assign_createScale',3,'p_assign_createScale','PySharp_Parse.py',22),
  ('assign_playScale -> playScale assign_createScale','assign_playScale',2,'p_assign_playScale','PySharp_Parse.py',31),
  ('assign_playScale -> playScale','assign_playScale',1,'p_assign_playScale','PySharp_Parse.py',32),
  ('assign_playScale -> playScale NAME','assign_playScale',2,'p_assign_playScale','PySharp_Parse.py',33),
  ('func -> assign_createScale','func',1,'p_func','PySharp_Parse.py',54),
  ('func -> assign_playScale','func',1,'p_func','PySharp_Parse.py',55),
  ('func -> HELP','func',1,'p_func','PySharp_Parse.py',56),
  ('func -> EXIT','func',1,'p_func','PySharp_Parse.py',57),
]
